### ISSUE TITLE
Error when inputting JSON via command line

### ISSUE THREAD

**Issue by facultymatt** [node-machine/machine#9]
When running my machine via the command line, I get an error when entering JSON for an input value. The error is: 

```
Error: `update-object-by-id` machine encountered 1 error(s) while validating runtime input values.
    at /Users/spmatt/sites/forks/machinepack-salesforce/node_modules/machine/lib/Machine.prototype.exec.js:53:19
    at Machine_prototype_exec [as exec] (/Users/spmatt/sites/forks/machinepack-salesforce/node_modules/machine/lib/Machine.prototype.exec.js:61:9)
    at Object.module.exports.fn (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/machines/run-machine.js:134:21)
    at _runMachine (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/Machine.prototype.exec.js:286:17)
    at afterCacheLookup (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/Machine.prototype.exec.js:293:7)
    at _cacheLookup (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/Machine.prototype.exec.js:165:25)
    at Machine_prototype_exec [as exec] (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/Machine.prototype.exec.js:216:5)
    at Object.Machine.build.exec.success (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/machines/run-machine-interactive.js:152:12)
    at afterwards (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/intercept-exit-callbacks.js:128:21)
    at null._onTimeout (/usr/local/lib/node_modules/machinepack/node_modules/machinepack-machines/node_modules/machine/lib/intercept-exit-callbacks.js:97:20)
```

The input `objectData` is required and the command line prompts me to enter it. I've tried multiple ways, for example

```
{"cats":"lolz"}     // error
"{'cats':'lolz'}"   // error
{cats:"lolz"}       // message, enter valid JSON (don't forget double quotes!)
```

**Comment by sgress454** [comment]
Can you post the definition of the machine you're trying this on? (Preferably as a [gist](http://gist.github.com)?)

**Comment by facultymatt** [comment]
See https://gist.github.com/facultymatt/f7f188f65b73856db168

**Comment by sgress454** [comment]
Based on the `example` for `objectData`, you JSON needs to include `FirstName` and `LastName` keys.  The example is meant for strongly-typed inputs.  If you want something a bit looser, you can use `{}` as the example for `objectData` (make sure you have the latest version `machine` for this).  This will stop the machine runtime from attempting to validate the input against a particular schema.

**Comment by mikermcneil** [comment]
@facultymatt note that @sgress454's comment is relevant as of `machine`@`>=9.0.0`

**Comment by mikermcneil** [comment]
btw @facultymatt I just wrote up some updated documentation [here](https://github.com/node-machine/rttc#types) which might be helpful
